### ISSUE TITLE
How to create a pipeline in a "team" using api

### ISSUE THREAD

**Issue by rhysawilliams2010** [buildkite/docs#111]
I'm looking at the API docs and trying to work out how to create a pipeline in a "team"
https://buildkite.com/docs/rest-api/pipelines#create-a-pipeline

It's unclear how to do this.

**Comment by keithpitt** [comment]
@rhysawilliams2010 howdy! Yeah it's a little hidden t the moment since teams is still in BETA. Adding teams to a pipeline is possible via REST - but it's a little tricky unfortunately...

The first step is to get the Team UUID's that you wanna add. The best way to do this is via the GraphQL API: http://graphql.buildkite.com - here's a guide on how to get started with it: https://building.buildkite.com/tutorial-getting-started-with-graphql-queries-and-mutations-11211dfe5d64

The query you wanna run is this:

```
query {
  organization(slug: "my-org-slug") {
    teams(first: 100) {
      edges {
        node {
          name
          uuid
        }
      }
    }
  }
}
```

This will give you a list of teams and their UUID's.

Once you've got them, you can send `team_ids` as an array within the "create-a-pipelie" REST API call. So something like this:

```
{
  "name": "My Awesome Pipeline",
  "repository": "git@github.com:my/repo.git",
  "steps": [ ... ],
  "team_ids": [ "568f2f97-0c81-4fb2-a915-dba5d0bddd3f", "88ce2d96-36d6-4ffd-8060-18698a8a718c" ]
}
```

Lemme know how you go! Will close for now. Feel free to comment on here again if you need a hand :)
