### ISSUE TITLE
Document how to use buildkite-agent behind a proxy

### ISSUE THREAD

**Issue by toolmantim** [buildkite/docs#140]
We don't document how to configure buildkite-agent’s HTTP proxy settings. This was just submitted by a user who went through the pain of figuring it out:

```
## Proxy.

If you are behind a proxy server you need to create a folder "/etc/system/system/buildkite-agent.service.d" and in there create a file called proxy.conf with your proxy settings inside it. You'll need to stop and start the service for the changes to take affect.
```

**Comment by nick040** [comment]
I have tried the suggestion above and I would like to add:
- There's a typo in the path above, the correct directory is in /etc/systemd (the d was missing), so that's: "/etc/systemd/system/buildkite-agent.service.d"
- The file proxy.conf must contain settings in systemd-unit format
- Example proxy.conf:

```
[Service]
# Proxy Env Vars
Environment=http_proxy=http://username:password@proxyserver:8080/
Environment=https_proxy=http://username:password@proxyserver:8080/
Environment=no_proxy=localhost,.example.com
```

Further help on systemd environment variables: https://coreos.com/os/docs/latest/using-environment-variables-in-systemd-units.html

**Comment by harrietgrace** [comment]
Thanks for the additions @nick040! 🙌🏻

**Comment by harrietgrace** [comment]
@lox are HTTP proxy settings still relevant to the v3 agent? If so, would this addition fit in with the Agent Configuration doc?

**Comment by lox** [comment]
Yup, still relevant! The http proxy stuff should probably be under “Running the agent behind a proxy” and then the systemd extension stuff perhaps under a systemd specific section in config? Systemd spans a few distros now.

**Comment by harrietgrace** [comment]
I did some more thinking about where those sections could sit in the docs - what do you think about having "running the agent behind a proxy" in Securing your Buildkite Agent, and "running multiple agents with systemd" in the top level How to Install Buildkite Agent?
