### ISSUE TITLE
Document how the agent gracefully restarts

### ISSUE THREAD

**Issue by lox** [buildkite/docs#170]
We are often asked how to restart the agent to pick up new configuration or how to shutdown agents without killing running tasks. This needs to be documented somewhere.

**Comment by lox** [comment]
Relevant to https://github.com/buildkite/agent/issues/476

**Comment by lox** [comment]
Also some description of what signals we handle and some nice descriptions like here: https://www.quora.com/What-is-the-difference-between-the-SIGINT-and-SIGTERM-signals-in-Linux-What%E2%80%99s-the-difference-between-the-SIGKILL-and-SIGSTOP-signals

**Comment by lox** [comment]
This is the canonical documentation presently: https://github.com/buildkite/agent/blob/ce7280de5d8fc20850f899bd4a1b23e6ced995f2/agent/agent_pool.go#L81

**Comment by lox** [comment]
Also, I just really like leaving comments on this issue.

**Comment by lox** [comment]
![llama](https://i.pinimg.com/564x/9c/5d/c4/9c5dc419fa2c3b24e452574447661f72--happy-animals-funny-animals.jpg)

**Comment by harrietgrace** [comment]
@lox we have a small section on [Signal Handling](https://buildkite.com/docs/agent/v3#signal-handling) in the overview document of the Agent. 

This section might be better with a little more context and in a different place - what do you think about an additional mention and a link to signal handling in the config doc and another in the buildkite-agent start doc? Otherwise I could just add a little more info to the current Signal Handling section so that the probable search terms like 'new config' or 'shutdown agents' will pop up in google with this section.

**Comment by harrietgrace** [comment]
👋🏻 @lox! Given that the 'stop agent' button is (somewhat recently) graceful and has the option for force stopping (https://github.com/buildkite/buildkite/pull/3064), do we need more docs additions about stopping agents? Possibly just a mention in the signal handling section that they can be killed from the Agent UI?
