### ISSUE TITLE
If multiple command hooks are found, all will be run

### ISSUE THREAD

**Issue by jeremiahsnapp** [buildkite/docs#438]
https://github.com/buildkite/docs/blob/master/pages/agent/v3/hooks.md.erb#L29 says

> If multiple command hooks are found, only the first will be run.

But when I use buildkite agent 3.4.0 and 3.8.4 and define multiple plugins for a step the agent runs the `command` hook of each plugin.

I'm fine having all `command` hooks run but can someone please confirm this is the correct behavior and update the docs? Thanks!

**Comment by ticky** [comment]
Hi @jeremiahsnapp, I just did a bit of a deep dive on this and you’re right, that’s totally confusingly worded.

I believe what’s gone on is that these docs were originally written before we added plugin support, and prior to plugins being added the statement was true - if you had multiple types of command hook (repository and agent, at the time) only the first would run.

The plugin hooks added a bit of a twist to the tale; if there’s a plugin hook, only plugin hooks will run (repository and agent will be ignored - as is the intent of the statement in the docs), but the plugin hook runner does indeed run every command hook (and, incidentally, every checkout hook) provided by your configured plugins.

Having dug into the code, thinking this was a regression, I discovered that this has in fact been the case (aside from the priority order of each of these hook types) since plugins were introduced way in buildkite/agent#200!

Given that, we’re going to have a discussion of what the right behaviour is here, so we can update the docs (and possibly behaviour) accordingly.

Anyway, thank you for reporting this, and I’m hoping we’ll get this addressed ASAP! 😃

**Comment by jeremiahsnapp** [comment]
@ticky Thanks for the awesome deep dive context. For what it's worth I like the flexibility of the behavior I'm seeing (running each plugin's command hook).

**Comment by harrietgrace** [comment]
Hey @jeremiahsnapp 👋🏻 Just wanted to give you a heads up that the next Agent release will be changing the behaviour of the plugin command hooks - if multiple are found in a step, only the first one will be run. We're on Agent v3.14.0 at the moment, so agents after that will have the new behaviour. 

If you've got any questions about the change let me know, or shoot through an email to support@buildkite.com 🙇🏻‍♀️
