### ISSUE TITLE
Update Documentation For Referencing Plugin Properties

### ISSUE THREAD

**Issue by mlfz9** [buildkite/docs#588]
It's not really clear in the documentation that if you include a plugin with the .git in the URL then the properties will need to be referenced with environment variable named `BUILDKITE_PLUGIN_{NAME}_GIT_{KEY}` instead of `BUILDKITE_PLUGIN_{NAME}_{KEY}` as documented

## Example 
For https://github.com/my-org/my-plugin.git#v1.0.0 I will need to use BUILDKITE_PLUGIN_MY_PLUGIN_GIT_MY_PROPERTY 
For https://github.com/my-org/my-plugin#v1.0.0 I will need to use BUILDKITE_PLUGIN_MY_PLUGIN_MY_PROPERTY

**Comment by justanotherdot** [comment]
+1 to this as I just ran into the same thing and only discovered what I needed to use by dumping `env` in my hook. Was overall frictionless up to that point.

**Comment by harrietgrace** [comment]
Hey @mlfz9 and @justanotherdot, thanks for letting us know! I'm just checking with the team if that behaviour is intended 😅 If so I'll get the docs updated with the extra info 👍🏻I'll leave this issue open for now.

**Comment by plannigan** [comment]
In general, there newly released plugin docs don't clearly explain the logic about how the environment variables are generated.

* I initially assumed it was based on the `name` field in `plugin.yml`, which I had set to `foo-bar-baz`. However, my repo was named `foo-bar-buildkite-plugin`. This caused the plugin to expect different environment variables names.
* A plugin I was using recently had it's repo renamed. Github creates redirects when a repo is renamed, so the old URL for the repo was still valid. However, the plugin was failing because the environment variables that were created didn't match what it expected, since it had been updated for the rename.
