### ISSUE TITLE
Updating pipeline steps through API doesn't work

### ISSUE THREAD

**Issue by robbalmbra** [buildkite/docs#777]
I am having the same issue as described here https://github.com/buildkite/docs/issues/628#issue-557168133, updating the steps of a pipeline doesn't work as described in the documentation here - https://buildkite.com/docs/apis/rest-api/pipelines#update-a-pipeline.

I have tried the below with no luck, it does not return an error only the unchanged yaml:

`curl -H "Authorization: Bearer $TOKEN" -X PATCH "https://api.buildkite.com/v2/organizations/rob-roms/pipelines/pe-deployment" -d '{"steps":[{"type":"script","command":"echo hello"}]}'`

**Comment by jayco** [comment]
Hey @robbalmbra sorry for the super late reply on this  :( 

This was related to a change we made using configuration value, there was also an issue raised in the forum https://forum.buildkite.community/t/pipeline-updates-through-api-dont-update-env/439. 

We have since updated the docs https://github.com/buildkite/docs/pull/808 to reflect the correct payload, apologies for the confusion around this.
