### ISSUE TITLE
Clear a pipeline's history and/or stats?

### ISSUE THREAD

**Issue by HariSekhon** [buildkite/docs#819]
Hi,

Is it possible to clear a pipeline's history and/or stats without deleting and recreating the pipeline? (which invalidates the ID/url/badges)

Preferably this should be possible via the API as well as UI but I didn't see anything about this in the API docs.

Thanks

Hari

**Comment by jayco** [comment]
Hey @HariSekhon good question and sorry for the late reply. 

At the moment it's not possible, but perhaps you could create a feature request here  https://forum.buildkite.community/c/feature-requests/11 with some context around the issues you are having.

You can also send us through an email at support@buildkite.com next time so that you get a more immediate response :)
