### ISSUE TITLE
depends_on/allow_failures does not block if a dependent step is stuck on failed dependencies

### ISSUE THREAD

**Issue by akursar** [buildkite/docs#840]
I have this pipeline:

    steps:
    
      - command: exit 1
        key: a
    
      - command: exit 0
        key: b
        depends_on:
          - step: a
    
      - command: exit 0
        key: c
        depends_on:
          - step: b
            allow_failure: true

Basically, there's A-> B ->C where B requires that A *succeeds*, and C requires that B *runs*. If A fails, I expect, and observe, that B does not run. However, when A fails, and B does not run, C *does* run even though B is blocked. Documentation (https://buildkite.com/docs/pipelines/dependencies#allowing-dependency-failures) says that allow_failure will run the step "when the depended-on jobs complete" but in this instance, the depended-on job did not complete. It is still waiting for A to succeed.

![Screen Shot 2020-10-14 at 2 46 40 PM](https://user-images.githubusercontent.com/1795603/96032052-24949800-0e2c-11eb-85c1-bca1d896977b.png)

I feel this is either a bug in behavior, or the documentation must be clarified if this is expected. If this is expected, is there another way to achieve my desired functionality?

**Comment by matthewd** [comment]
Hey @akursar -- sorry about the delay in getting an answer here.

This is indeed expected behaviour (agreed, the documentation could better communicate what happens in this sort of interaction).

Internally, while it's not a visible distinction in the UI, when job A fails, job B transitions from the `waiting` state to `waiting_failed` (it _was_ waiting, but is now unable to run due to a preceding failure). That counts for the purposes of `allow_failure`, and thus job C is allowed to run.

This is the intended result because it allows you to select either behaviour, depending on which you want: if it worked the other way, there'd be no practical way to indicate that you did actually want job C to still run. As it is, however, you can _prevent_ job C from running by adding an additional (non-`allow_failure`) dependency from C to A: thus, C will run after 1) A has completed successfully, and 2) B has reached any final state.


```
  - command: exit 0
    key: c
    depends_on:
      - step: a
      - step: b
        allow_failure: true
```

**Comment by akursar** [comment]
Understood. Thanks for the explanation @matthewd . Adding the extra dependencies is what we've been doing but have been treating as a workaround. It works, but we now have to manage those transitive dependencies.
I think that if those states are documented (waiting, waiting_failed) and the behavior for allow_failure includes those states, that would help.
Further, if those states were exposed and we could potentially use them in a more advanced step dependency configuration where we could explicitly say we require one of success or failed states or something like that, that would give us more control and provide for what I think are more clear expectations.
I think that would also help with excluded tasks. For example, as the documentation says, "However, if the step you're dependent on is excluded from the build due to an if condition, the dependency will be ignored and the step that depends on it will run once any other dependencies are satisfied." I believe that the situation here is the same, where if A has an IF conditional and B requires that A *succeeds*, you'd need that same conditional applied to B to assert that B won't run if A's IF conditional excludes it from the build.
Does that make sense? If so, and you think it might be interesting to propose, is there a place where I can submit as a feature request/enhancement?

**Comment by plaindocs** [comment]
Hi @akursa, thanks for reporting. I've added some docs in #879, take a look at let me know if you think there is room for improvement.
