### ISSUE TITLE
Writing Plugins out of date with buildkite/plugin-tester

### ISSUE THREAD

**Issue by amukherjeetwilio** [buildkite/docs#868]
It looks like https://buildkite.com/docs/plugins/writing is out of date with respect to https://github.com/buildkite-plugins/buildkite-plugin-tester/blob/master/README.md. Specifically it looks like buildkite/plugin-tester now uses a different version of bats-mock which has completely different semantics for their stub method, which looks like

```
  stub buildkite-agent "annotate 'Found 1 files matching *.bats' : echo stubbed"
```

whereas the **Writing Plugins** guide describes that you should use 
```
  stub buildkite-agent annotate "Found 1 files matching *.bats"
```

This is specifically unfortunate since the incorrect version outputs the incredibly non-useful:
```
❯ docker-compose run --rm tests
Creating rpm-buildkite-plugin_tests_run ... done
 ✗ Creates an annotation with the file count
   (from function `unstub' in file /usr/local/lib/bats/bats-mock/stub.bash, line 35,
    in test file tests/post-command.bats, line 14)
     `unstub buildkite-agent' failed
   BUILDKITE_AGENT_STUB_DEBUG

1 test, 1 failure
```

**Comment by toolmantim** [comment]
Thanks for the report @amukherjeetwilio, and sorry for that typo. I gave it a local test, verified that bug, and pushed up a fix. I also added an example commented out line for helping to debug stub failures, because bats-mock doesn’t give very useful failures without it. Sorry again for it being incorrect!
